name: Build mod

on:
  pull_request:
    branches: "*"
  workflow_dispatch:

jobs:
  build:

    runs-on: windows-latest
    env:
      PROJECT_NAME: jcdcdev.Eco.SeedStorage
      PROJECT_PATH: ./src/Server/jcdcdev.Eco.SeedStorage.csproj
      BUILD_OUTPUT: ./build-output
      MOD_OUTPUT: ./build-assets/Mods/jcdcdev.Eco.SeedStorage
      ASSET_NAME: jcdcdev.Eco.SeedStorage-dev-${{ github.sha }}
    steps:
      - name: Checkout repository
        uses: actions/checkout@v3
      - name: Setup .NET
        uses: actions/setup-dotnet@v2
        with:
          dotnet-version: 7.0.x
      - name: Build project
        run: dotnet build ${{ env.PROJECT_PATH }} -o ${{ env.BUILD_OUTPUT }} --configuration Release
      - name: Copy Unity Assets
        run: |
          mkdir "${{ env.MOD_OUTPUT }}"
          cp "./src/Client/BuildOutput/${{ env.PROJECT_NAME }}.unity3d" "${{ env.MOD_OUTPUT }}"      
          cp "${{ env.BUILD_OUTPUT }}/${{ env.PROJECT_NAME }}.dll" "${{ env.MOD_OUTPUT }}"      
      - uses: vimtor/action-zip@v1
        with:
          files: ${{ env.MOD_OUTPUT }}/
          dest: ${{ env.ASSET_NAME }}.zip
          recursive: false
      - name: Upload package
        uses: actions/upload-artifact@v2
        with:
          name: ${{ env.ASSET_NAME }}
          path: ${{ env.ASSET_NAME }}.zip
