name: Build mod

on:
  pull_request:
    branches: "*"
  workflow_dispatch:

jobs:
  build:

    runs-on: windows-latest

    steps:
      - name: Checkout repository
        uses: actions/checkout@v3
      - name: Setup .NET
        uses: actions/setup-dotnet@v2
        with:
          dotnet-version: 7.0.x
      - name: Build project
        run: dotnet build ./src/Server/jcdcdev.Eco.SeedStorage.csproj -o build-output --configuration Release
      - name: Copy Unity Assets
        run: |
          mkdir "./build-assets/Mods/jcdcdev.Eco.SeedStorage"
          cp "./src/Client/BuildOutput/jcdcdev.Eco.SeedStorage.unity3d" "./build-assets/Mods/jcdcdev.Eco.SeedStorage"      
          cp "./build-output/jcdcdev.Eco.SeedStorage.dll" "./build-assets/Mods/jcdcdev.Eco.SeedStorage"      
      - uses: vimtor/action-zip@v1
        with:
          files: ./build-assets/
          dest: jcdcdev.Eco.SeedStorage-dev-${{ github.sha }}.zip
      - name: Upload package
        uses: actions/upload-artifact@v2
        with:
          name: jcdcdev.Eco.SeedStorage-dev-${{ github.sha }}
          path: jcdcdev.Eco.SeedStorage-dev-${{ github.sha }}.zip
