name: build mod

on:
  pull_request:
    branches: "*"
  workflow_dispatch:

jobs:
  build:

    runs-on: windows-latest

    steps:

      - name: Checkout repository
        uses: actions/checkout@v3

      - name: Setup .NET
        uses: actions/setup-dotnet@v2
        with:
          dotnet-version: 7.0.x

      - name: Build project
        run: dotnet build ./Server/jcdcdev.Eco.SeedStorage.csproj -o build-assets --configuration Release
      - uses: vimtor/action-zip@v1
        with:
          files: ./build-assets/jcdcdev.Eco.SeedStorage.dll ./src/Client/BuildOutput/jcdcdev.Eco.SeedStorage.unity3d
          dest: jcdcdev.Eco.SeedStorage-dev-${{ github.sha }}.zip
      - name: Upload package
        uses: actions/upload-artifact@v2
        with:
          name: jcdcdev.Eco.SeedStorage-dev-${{ github.sha }}
          path: jcdcdev.Eco.SeedStorage-dev-${{ github.sha }}.zip
