name: '📚 Sync mod.io README and Images'
on:
  workflow_dispatch:
  repository_dispatch:
    types: [ sync-readme ]
jobs:
  sync_modio:
    runs-on: ubuntu-latest
    name: 'Sync mod.io README and Images'
    permissions:
      contents: write
      pull-requests: write
    steps:
      - name: Checkout repository
        uses: actions/checkout@v4
        with:
          fetch-depth: 0
      - name: Update README
        shell: pwsh
        run: |
          $result = ./src/get-version-table.ps1 -projectFilePath "./src/Server/jcdcdev.Eco.SeedStorage.csproj"
          Write-Host "result=$result"

          git config user.name "$env:GITHUB_ACTOR"
          git config user.email "$env:GITHUB_ACTOR_ID+$env:GITHUB_ACTOR@users.noreply.github.com"
          git checkout ${{ github.ref }}
          git commit -m "doc: Update version table"
          
          $readme = Get-Content -Path ".github/README.md"
          $readme = $readme -replace "(?s)(?<=## Version Table).*", $result
          
          Write-Host "new readme=$readme"
          
          $readme | Set-Content -Path ".github/README.md"
          git push origin ${{ github.ref }}
      - name: Sync with mod.io
        uses: jcdcdev/jcdcdev.Modio.SyncDocs@main
        with:
          logo-path: "docs/logo.png"
          images-path: "docs/screenshots"
          readme-path: ".github/README.md"
          project-author: "JCDC DEV"
          project-name: "SEED STORAGE"
          imejis-generate-image: true
          imejis-design-id: "${{ secrets.DESIGN_ID }}"
          imejis-key: "${{ secrets.IMEJIS_KEY }}"
          modio-game: "${{ secrets.MODIO_GAME }}"
          modio-mod: "${{ secrets.MODIO_MOD }}"
          modio-token: "${{ secrets.MODIO_TOKEN }}"     
            
      