name: Update modio mod description
on:
    workflow_dispatch:

jobs:
    update_mod_description:
        runs-on: ubuntu-latest
        steps:
            - name: Checkout code
              uses: actions/checkout@v2
            - name: Install tools
              run: |
                sudo apt-get install pandoc
                sudo apt-get install jq
            - name: Convert README to HTML
              id: convert
              run: | 
                pandoc .github/README.md -o README.html
                README_HTML_SINGLE_LINE=$(cat README.html | tr '\n' ' ')
                README_ENCODED=$(echo -n "$README_HTML_SINGLE_LINE" | jq -s -R -r @uri)
                echo "README_HTML=$(printf '%q' "$README_ENCODED")" >> $GITHUB_ENV
            - name: Update modio mod description
              run: |
                curl -X PUT 'https://api.mod.io/v1/games/${{ secrets.MODIO_GAME }}/mods/${{ secrets.MODIO_MOD }}' \
                -H 'Authorization: Bearer ${{ secrets.MODIO_TOKEN }}' \
                -d "description=${{ env.README_HTML }}"
            - name: Upload logo to mod.io
              run: |
                if [ -f "docs/logo.png" ]; then
                    curl -X POST "https://api.mod.io/v1/games/${{ secrets.MODIO_GAME }}/mods/${{ secrets.MODIO_MOD }}/media" \
                    -H 'Authorization: Bearer ${{ secrets.MODIO_TOKEN }}' \
                        -H 'Content-Type: multipart/form-data' \ 
                        -H 'Accept: application/json' \
                        -F "logo=@docs/logo.png"
                else
                    echo "docs/logo.png does not exist"
                fi
            - name: Upload images to mod.io
              run: |
                index=0
                for file in docs/screenshots/*; do
                    curl -X POST "https://api.mod.io/v1/games/${{ secrets.MODIO_GAME }}/mods/${{ secrets.MODIO_MOD }}/media" \
                    -H 'Authorization: Bearer ${{ secrets.MODIO_TOKEN }}' \
                    -H 'Content-Type: multipart/form-data' \ 
                    -H 'Accept: application/json' \
                    -F "image$index=@$file"
                    index=$((index+1))
                done
